#!/usr/bin/env python3
"""Generate a real-content ramdisk for Polisite OS (Phase 0 test asset).

Produces a tar containing:
  - splash.rgb : a real, deterministic RGB gradient image (viewable, not padding)
  - the project's own DESIGN.md / ROADMAP.md / README.md / LICENSE (real docs)

The resulting tar is ~RAMDISK_MB megabytes so the kernel binary and the ISO
are realistically sized for boot/install testing. It is regenerated by
build/build.sh before compiling the kernel.

Usage: tools/make_assets.py [out_dir] [ramdisk_mb]
"""
import os
import sys
import tarfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(REPO_ROOT, "kernel", "src")
RAMDISK_MB = int(os.environ.get("RAMDISK_MB", "96"))


def make_splash(path: str, target_bytes: int) -> int:
    """Write a vertical RGB gradient image (real, viewable content).

    Dimensions are chosen so the raw image is ~target_bytes. One row is built
    as a bytes object and written repeatedly, so this is fast even at 100 MB.
    """
    width = 4096
    row_bytes = width * 3
    height = max(1, target_bytes // row_bytes)
    with open(path, "wb") as f:
        for y in range(height):
            # vertical gradient: red rises, blue falls, green is a soft sine
            t = y / max(1, height - 1)
            r = int(20 + 215 * t)
            b = int(235 - 200 * t)
            g = int(40 + 90 * (0.5 + 0.5 * (1 - abs(2 * t - 1))))
            row = bytes([r, g, b]) * width
            f.write(row)
    size = height * row_bytes
    return size


def main() -> None:
    out_dir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUT
    ramdisk_mb = int(sys.argv[2]) if len(sys.argv) > 2 else RAMDISK_MB
    os.makedirs(out_dir, exist_ok=True)

    splash = os.path.join(out_dir, "splash.rgb")
    # Leave room in the tar for the docs (~a few hundred KB).
    splash_size = make_splash(splash, ramdisk_mb * 1024 * 1024 - 512 * 1024)

    tar_path = os.path.join(out_dir, "embedded_ramdisk.tar")
    doc_names = ["docs/DESIGN.md", "docs/ROADMAP.md", "README.md", "LICENSE"]
    with tarfile.open(tar_path, "w") as tar:
        tar.add(splash, arcname="splash.rgb")
        for d in doc_names:
            p = os.path.join(REPO_ROOT, d)
            if os.path.exists(p):
                tar.add(p, arcname=os.path.basename(d))

    tar_size = os.path.getsize(tar_path)
    print(f"assets: splash.rgb = {splash_size:,} B, ramdisk = {tar_size:,} B "
          f"({tar_size / (1024 * 1024):.1f} MiB)")


if __name__ == "__main__":
    main()
